// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {repo} from '../models';

export function CreateTask(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DeleteTask(arg1:string):Promise<void>;

export function ListTasks():Promise<Array<repo.Task>>;

export function UpdateTask(arg1:repo.Task):Promise<void>;
